### PR TITLE
npm packge update v10.x to v13.x

### PR DESCRIPTION
**Pull request by gurezo**
### 
i had to update this repository npm package v10.x to v13.x

### reson why?

- today(2022.04.23) there was an event in the mdn translation community Japan
- today(2022.04.23) , i had translate document en-us to ja
- i had to find example v10.x
- i'm able to upgrade angular version.

### for referrence
- [Getting started with Angular en-us to ja PR](https://github.com/mdn/translated-content/pull/5228)
- [Getting started with Angular en-us to ja](https://github.com/mozilla-japan/translation/issues/595)
- [Understanding client-side JavaScript frameworks en-us to ja]( https://github.com/mozilla-japan/translation/issues/599)

### CODE REVIEW

**Comment by gurezo** [comment]
today, tranlation japanese PR merged.

**Comment by kapunahelewong** [comment]
Hey @gurezo, thank you for this PR. May I ask how you came across this repo? It was originally the source for the MDN Getting Started with Angular and they used to have a fork of it along with their other framework todo apps, but I'm not finding it there when I search. I no longer work on Angular docs so this repo has, as you can tell, become very outdated and shouldn't be relied on to accompany that tutorial. Could you share with me how you found it? Maybe I can reach out to someone to see about seeing which repo would be better for your PR.

**Comment by gurezo** [comment]
Hi kapunahelewong
The following pages have been translated by the MDN translation community in Japan on 2022.04.23.
https://mozilla.doorkeeper.jp/events/134498

Here is the page translated into Japanese.

- https://developer.mozilla.org/ja/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks
    - this section note part: 
        - https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks#angular_tutorials
    - When I translated this page, I noticed the existence of a sample code repository
- https://developer.mozilla.org/ja/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_getting_started

That's all for discovering the repository, upgrading the version, and creating a PR.
kind regards

**Comment by kapunahelewong** [comment]
Ah, thank you so much for the info, @gurezo . I have filed [an issue](https://github.com/mdn/content/issues/15877) with MDN. Hopefully they'll consider taking this example into their github like the other ones. If you'd also like to fork and maintain on your end, please do. If you decide to take it, please let me know and I will link in the readme to yours. I'll merge this. Thanks for your contribution.

**Pull request merged**
